
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: ${KV_USER_ASSIGNED_CLIENT_ID}  
  name: ${KV_SERVICE_ACCOUNT_NAME}
  namespace: ${KV_SERVICE_ACCOUNT_NAMESPACE}