apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-wi
  namespace: default
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    clientID: ${KV_USER_ASSIGNED_CLIENT_ID}  # Setting this to use workload identity
    keyvaultName: "${KEY_VAULT_NAME}"
    cloudName: ""                   # Optional: Defaults to AzurePublicCloud
    tenantId: ${KV_IDENTITY_TENANT} # Tenant ID of the Key Vault
    objects: |
      array:
        - |
          objectName: mysql-db-username
          objectType: secret        # object types: secret, key, or cert
          objectVersion: ""         # Optional: Default to latest if empty
        - |
          objectName: mysql-db-password
          objectType: secret
          objectVersion: ""
        - |
          objectName: DigiCertGlobalRootCA
          objectType: secret
          objectVersion: ""         # Empty means the latest version of the secret
  secretObjects:
    - secretName: secrets-store-webops
      type: Opaque
      data:
        - objectName: mysql-db-username
          key: mysql-db-username
        - objectName: mysql-db-password
          key: mysql-db-password
        - objectName: DigiCertGlobalRootCA
          key: DigiCertGlobalRootCA.crt.pem